name: Build wheel and sdist for a non-pure Python package

on:
  workflow_call:

jobs:
  # FIX ME
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: hynek/build-and-inspect-python-package@v2