name: Build Wheel, Release, Upload

on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the project to test'
        default: 'PROJECT_NAME'
        required: false
        type: string
      c_extension:
        description: 'Whether the project has a C extension'
        default: false
        required: false
        type: boolean
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true
      PAT_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  update-changelog:
    # The always() function is necessary to ensure that we wait for both build jobs to complete, even if one of them is skipped.
    # Without always(), if one of the needed jobs is skipped, the `update-changelog` job will not be executed.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update CHANGELOG.rst with the latest news
        run: |
          wget https://raw.githubusercontent.com/bobleesj/release-scripts/ignore-no-news/.github/workflows/update-changelog.py
          python update-changelog.py "${{ github.ref_name }}"
          rm update-changelog.py

      - name: Commit the changes in CHANGELOG.rst
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update changelog
          branch: main
